# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4121009736b00562f119e8d41bb9cf29a572642f76a4c7da70b8cc31b73ccde97e64fea29cbecc2965426f91bb7224df67b8d15bd704ad9b15c94d376289eb4a

test:
  secret_key_base: 84ae1faf809b808fea9eff70b2708d3c13979bd36fadac1c62e80211e981f558be36b95456fba36c285977f516f3bbd1600d63d04801648cbedd9c4eff90d84d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
